Frequentemente, utilizamos números armazenados no formato de ponto flutuante. Essa representação possui precisão finita, como ilustrado no exemplo a seguir:

In [ ]:
x_int = 553
x_float = 553.089

print("Variável x_int =", x_int,  "->", type(x_int))
print("Variável x_float =", x_float, "->", type(x_float))

Variável x_int = 553 -> <class 'int'>
Variável x_float = 553.089 -> <class 'float'>


Aqui, temos duas variáveis: um inteiro, do tipo int (553), e um número decimal (553.089), do tipo float (ponto flutuante)

In [ ]:
print("Tamanho de x_int obtido por sys.getsizeof(int) =", sys.getsizeof(x_int), "bytes")
print("Tamanho de x_float obtido por sys.getsizeof(float) =", sys.getsizeof(x_float), "bytes")
print("float64 epsilon  =", np.finfo(np.float64).eps)

eps = np.finfo(np.float64).eps
print("1 + epsilon > 1: ", 1 + eps > 1)
print("1 + epsilon/2 > 1: ",1 + eps/2 > 1)

Tamanho de x_int obtido por sys.getsizeof(int) = 28 bytes
Tamanho de x_float obtido por sys.getsizeof(float) = 24 bytes
float64 epsilon  = 2.220446049250313e-16
1 + epsilon > 1:  True
1 + epsilon/2 > 1:  False


Acima, vemos espaço ocupado pelas variáveis que criamos. Além disso, obtemos o valor do epsilon do float, ou seja, a diferença entre 1 e o menor float representável maior do que 1. Esse valor possui aproximadamente 16 dígitos decimais.

In [ ]:
a = 0.1 + 0.2
print("a = 0.1 + 0.2 =", a)
print("a == 0.3:", a == 0.3)
print("Variável a com 20 casas decimais:", format(a, ".20f"))
print("math.isclose(a, 0.3):", math.isclose(a, 0.3))

a = 0.1 + 0.2 = 0.30000000000000004
a == 0.3: False
Variável a com 20 casas decimais: 0.30000000000000004441
math.isclose(a, 0.3): True


Encontramos um clássico problema da representação em ponto flutuante: a soma entre 0.1 e 0.2 não resulta em 0.3 — inclusive, a comparação `0.1 + 0.2 == 0.3` retorna `false`.
A função `math.isclose()` retorna `true`, pois possui um nível de tolerância na comparação, sendo especialmente útil para casos como esse




# Exemplo Extra

In [ ]:
medida_real = 539.089 #metros
precisao_aparelho = 0.1 # só consegue ler com precisao de 10 cm

print(f"Objeto mede {medida_real} m")
print(f"Resolucao do aparelho: {precisao_aparelho} m")

amostras = [-0.03423461, -0.01369362,  0.00379222,  0.03081551,  0.02535254]
soma=0
for amostra in amostras:
  soma += (medida_real+amostra)
media_bruta = soma / len(amostras)

print("-"*30)
print(f"Média Bruta (Falsa Precisão): {media_bruta:.15f} m")
media_precisa = round(media_bruta, 1)
print(f"Média precisa (levando em conta a precisão do aparelho): {media_precisa} m")  # medida de acordo com  a precisão do aparelho

# imagine que haja um limite de 0.01m (como um procedimento de segurança) entre a média e o objeto
# para a média e a medida real, ao cruzar esse limite deve-se apontar como false (nao seguro)
limite_tol = 0.01
testbruto = math.isclose(media_bruta, medida_real, abs_tol=limite_tol)
testpreciso = math.isclose(media_precisa, medida_real, abs_tol=limite_tol)

print(f"A medição com base na média bruta esta dentro do limite: {testbruto}")
print(f"A medição com base na média precisa esta dentro do limit: {testpreciso}")

# o que isso significa: a media bruta tem uma falsa precisão,  uma vez que o aparelho só mede com
# precisão uma casa depois da virgula, não faz sentido
# usar todos os decimais daquela medida, usando a medicao bruta vemos que da true

# Isso é uma falha de segurança já que levando em conta a precisão do instrumentoo devia dar false
# isto é, não seguro.

Objeto mede 539.089 m
Resolucao do aparelho: 0.1 m
------------------------------
Média Bruta (Falsa Precisão): 539.091406408000125 m
Média precisa (levando em conta a precisão do aparelho): 539.1 m
A medição com base na média bruta esta dentro do limite: True
A medição com base na média precisa esta dentro do limit: False
